### ISSUE TITLE
Various labs clean-up tasks

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-web#69]
# TODO

- [ ] Remove the "Use the tabs below to use this lesson's resources" banner
- [ ] simplify the buttons to be smaller, and hideable, especially on mobile
- [ ] the mouse for guacamole sessions extends into the tab header area
- [ ] the guacamole keyboard is overcontrolling - prevents us from using Ctrl+C and such for lesson guide content
- [ ] See how easy it is to get mobile working. Collapse lesson guide or jupyter notebook into a tab
